- README.md
- checkpackages.py
- csvtojson.py
- deployInsightAgent.py
- getmetrics.sh
- initconfig.py
- installInsightAgent.py
- startcron.py
Summary of changes:
1) Changed deployment code to downloads other 2 scripts needed for deployment. Previously the use has to download 3 scripts and then start deployment. Now they can download one script and start deployment.
2) Script to check if pexpect and request python packages are installed in all hosts. If not install in appropriate hosts.
3) Add key based authentication for ssh in addition to password authentication.
> Monitoring

- common/reportMetrics.py
- daemonset/getmetrics_daemonset.py
- deployment/deployInsightAgent.py
- deployment/install.sh
- deployment/installInsightAgent.py
- deployment/startcron.py
- replay/README.md
Renamed csvtojson to reportMetrics.py.
Change in kubernetes daemonset agent which is moved from private repo.
> Changes from private repo on renaming projectkey to licensekey:

- cadvisor/getmetrics_cadvisor.py
Previously the cadvisor agent was specific to work only with
CCM project. Now it can get metrics for all docker containers.
> Cadvisor agent to get metrics for all docker containers:

- proc/getmetrics.sh
- proc/getmetrics_proc.py
Get diskused metrics both aggregated and individual partition metrics.
Also get loadavg over 1 min, 5 min, 15 mins.
Assign groupid in sampling code rather than in reporting code like other
agents.
> Get diskused per partiton:

- common/reportMetrics.py
For logfilereplay agent, agenttype is also sent.
> Report chunkserialnumber, total chunknumber for replay agents:

- cadvisor/README.md
- cgroup/README.md
- collectd/README.md
- deployment/AgentMaster/roles/install/tasks/main.yml
- docker_remote_api/README.md
- ec2monitoring/README.md
- elasticsearch-storage/Readme.md
- elasticsearch/README.md
- hypervisor/README.md
- kafka/Readme.md
- proc/README.md
Updating readme to use customserver url with deployInsightAgent
> Updating readme to use customserver url with deployInsightAgent

- deployment/DeployAgent/Readme.md
- deployment/DeployAgent/insightagent.yaml
- deployment/DeployAgent/inventory
- deployment/DeployAgent/roles/install/files/downloadAgent.sh
- deployment/DeployAgent/roles/install/tasks/main.yml
- deployment/DeployAgent/roles/uninstall/tasks/main.yml
Updating ansible to take home from ansible variable and not assume /home/user
Update Readme
> Updating Ansible to take home path from Ansible variable

- common/reportMetrics.py
- deployment/install.sh
Adding second level granularity for sampling and reporting interval
> Adding second level granularity for sampling and reporting interval

- common/reportMetrics.py
add fileID in response for metric replay
> add fileID field in reportMetric.py

- deployment/DeployAgent/roles/install-tdagent/tasks/main.yml
td-agent installer refactoring
> refactoring

- proc/getmetrics.sh
- proc/getmetrics_proc.py
- statsite/insightfinder.py
added filter for rn_app
added rolling log
> 870 add filter

- kafka/getmetrics_kafka.py
Details are in the [Jira](https://insightfinders.atlassian.net/browse/II-1819)
> II-1819 Add check of whether all metrics are collected for a certain timestamp

- kafka_logs/getlogs_kafka.py
> Ii 1940 enhance kafka agent

- deployment/DeployAgent/inventory
- deployment/DeployAgent/roles/install-opentsdb/tasks/main.yml
- deployment/DeployAgent/roles/install-opentsdb/templates/config.ini
- deployment/DeployAgent/roles/install-opentsdb/templates/config.txt
- deployment/install.sh
- kafka/getmetrics_kafka.py
- opentsdb/README.md
- opentsdb/getmetrics_opentsdb.py
> II 2225 opentsdb

- common/config.ini
- common/reportMetrics.py
1.  check whether message field is json format and then do the filtering.
2. user can specify the fields he/she wants for data field
> II 2306 add customized data fields for log replay

- deployment/install.sh
- hbase/config.ini.template
- hbase/getmetrics_hbase.py
> II 2529 - HBase agent

- common/reportMetrics.py
- logFileReplay/README.md
- metricFileReplay/README.md
- reporting_config.json
hardcoding instance and assuming logs will be replayed in the same year.
> handle network logs

- deployment/DeployAgent/roles/install-filebeat/tasks/setup-RedHat.yml
- deployment/DeployAgent/roles/install-logstash/files/filters/15-cassandra.conf
- deployment/DeployAgent/roles/install-logstash/files/filters/16-jetty.conf
- deployment/DeployAgent/roles/install-logstash/files/filters/90-cloudtrail.conf
- deployment/DeployAgent/roles/install-logstash/tasks/config-aws-key.yml
- deployment/DeployAgent/roles/install-logstash/tasks/config-gcp-key.yml
- deployment/DeployAgent/roles/install-logstash/tasks/plugins.yml
- deployment/DeployAgent/roles/install-logstash/tasks/setup-RedHat.yml
- deployment/DeployAgent/roles/install-logstash/templates/21-s3-input.conf.j2
- deployment/DeployAgent/roles/install-logstash/templates/22-pubsub-input.conf.j2
- deployment/DeployAgent/roles/install-logstash/templates/91-pubsub.conf.j2
errors typically due to logstash already being installed
> keyfile-related fixes

- file_replay/csv/replay_csv.py
split out regex. xml will be in a different PR
> 5879-regex-delim

- rabbitmq-metric/logstash-config/input-beats.conf
- rabbitmq-metric/logstash-config/metric-rabbitmq.conf
- rabbitmq-metric/logstash-config/output-http.conf
logstash config for rabbitmq connection metric ingestion
> 5998 metricbeat rabbitmq

- collectd/collectdReportMetrics.py
add more debug info for python collectd agent
> ii-7225 investigate data loss on staging  

- kafka2/getmessages_kafka2.py
Reverts insightfinder/InsightAgent#307
Missed the label_message method which converts the csv entry to a json object, so the original was correct.
> Revert "fix csv message"

- demo_system/constant.py
- demo_system/data_replay.py
- demo_system/demo_controller.py
- add alert project
- add timestamp support
- add same instance as the alert project in the metric project
> Demo system optimization

- prometheus-new/getmessages_prometheus-new.py
Ticket has been updated to only update the prometheus agent for this update. 
The agent will create a local sqlite3 cache with a mapping of the instance name to an alias.  If there are multiple instance names for the same instance with different metrics, you can set the alias in the db to be the same and it will merge the instances into a single instance. 
This assumes unique metrics between the instances that are being merged.
> Ii 8930 add instance component lookup em7 prometheus

- demo_system/constant.py
- demo_system/data_replay.py
- demo_system/demo_controller.py
Testing instruction:
https://insightfinders.atlassian.net/browse/II-8970
> II-8970 New demo system

- logstash-offline/README.md
- logstash-offline/roles/logstash-ansible/defaults/main.yml
- logstash-offline/roles/logstash-ansible/tasks/install-logstash.yaml
squashed additional bugs concerning file permissions and dir creation and added more info to readme
> Additional bug fixes

- k8s_logs/README.md
- k8s_logs/config.ini.template
- k8s_logs/getlogs_k8s.py
> ii-10921 revise kubernetes log agent 

- elasticsearch_collector/getmessages_elasticsearch_collector.py
Added code to based on below cases:
Single data field:
If data - set value
If no data - return empty string
Multiple data fields:
if data - set value
if no data for one field - drop value
if no at all - return empty string
> Ii 12483 data fields Update

- prometheus/README.md
Updated Prometheus ReadMe to remove older config variables and add new metric query variable
> Ii 12680 - Update Prometheus ReadMe

- aws-s3/getmessages_metric.py
jira: https://insightfinders.atlassian.net/browse/II-13669
> II-13669: parse s3 agent log data

- vCenter/vCenter.py
https://insightfinders.atlassian.net/browse/II-13881
> II-13881: Reconstruct chunk sizing logic for vCenter agent;

- td-agent/out_InsightFinder.rb
jira: https://insightfinders.atlassian.net/browse/II-14156
- Fix data showing up null
- Fix instance name can't be set
> II-14156: update Fluentd plugin logic;

- TeamsTestingUtil/.gitignore
- TeamsTestingUtil/README.md
- TeamsTestingUtil/config.properties
- TeamsTestingUtil/mvnw
- TeamsTestingUtil/mvnw.cmd
- TeamsTestingUtil/pom.xml
- TeamsTestingUtil/src/main/java/com/insightfinder/util/UtilApplication.java
- TeamsTestingUtil/src/main/java/com/insightfinder/util/Utils/Utils.java
- TeamsTestingUtil/src/main/java/com/insightfinder/util/config/Config.java
- TeamsTestingUtil/src/main/java/com/insightfinder/util/controller/TestController.java
- TeamsTestingUtil/src/test/java/com/insightfinder/util/UtilApplicationTests.java
https://insightfinders.atlassian.net/browse/II-14283
> II-14283 Teams Testing Util

- KafkaCollectorAgent/README.md
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/KafkaCollectorAgentApplication.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/DataInTimestamp.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/IFProjectManager.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/IFStreamingBuffer.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/IFStreamingBufferManager.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/InstanceData.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/KafkaConsumerManager.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/MetricDataPoint.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/MetricHeaderEntity.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/StreamingBuffers.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/UtilsBeans.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/config/IFConfig.java
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/config/KafkaConfig.java
https://insightfinders.atlassian.net/browse/II-14424
> II-14424 Update kafka agent for log

- td-agent/out_InsightFinder.rb
Missing an end in the ruby statement
> add missing end in ruby code

- KafkaCollectorAgent/config-log-template.properties
- KafkaCollectorAgent/config-metric-template.properties
- KafkaCollectorAgent/src/main/java/com/insightfinder/KafkaCollectorAgent/logic/IFStreamingBufferManager.java
https://insightfinders.atlassian.net/browse/II-14763
> II-14763 Kafka log support

- event_push/Dockerfile
- event_push/README.md
- event_push/entrypoint.sh
- event_push/helm_chart/.helmignore
- event_push/helm_chart/Chart.yaml
- event_push/helm_chart/templates/configMap.yaml
- event_push/helm_chart/templates/deployment.yaml
- event_push/helm_chart/values.yaml
Jira: https://insightfinders.atlassian.net/browse/II-14952
> [II-14952] Create helm chart for event push agent.

- dell_power_collector/conf.d/config.ini.template
- dell_power_collector/helper.go
- dell_power_collector/main.go
Add a blacklist field for instance in the setting.
jira: https://insightfinders.atlassian.net/browse/II-14930
> II-14930 skip certain instance name

- vCenter/Dockerfile
- vCenter/entrypoint.sh
- vCenter/helm_chart/.helmignore
- vCenter/helm_chart/Chart.yaml
- vCenter/helm_chart/README.md
- vCenter/helm_chart/templates/config-ini-cm.yaml
- vCenter/helm_chart/templates/deployment.yaml
- vCenter/helm_chart/values.yaml
Jira: https://insightfinders.atlassian.net/browse/II-14952
> Create helm chart for vcenter agent

- event_push/helm_chart/templates/configMap.yaml
- event_push/helm_chart/templates/deployment.yaml
- event_push/helm_chart/values.yaml
Enable multiple configuration files for eventPush agent helm chart.
> Enable multiple configuration files for eventPush agent helm chart.

- kubernetes-agent/insightfinder/logDataModel.go
- kubernetes-agent/loki/dataModel.go
- kubernetes-agent/loki/loki.go
- kubernetes-agent/main.go
- kubernetes-agent/tools/LogData.go
- kubernetes-agent/tools/utility.go
Jira: https://insightfinders.atlassian.net/browse/II-15081
> Add K8Identity field in json payload for Log data.

- demo_system/data_replay-stg.py
- demo_system/data_replay.py
postpone the log anomaly data sending time for 5 mins
> update the demo system

- kubernetes-agent/helm_chart/Chart.yaml
- kubernetes-agent/helm_chart/README.md
- kubernetes-agent/helm_chart/templates/clusterRole.yaml
- kubernetes-agent/helm_chart/templates/clusterRoleBinding.yaml
- kubernetes-agent/helm_chart/templates/configMap.yaml
- kubernetes-agent/helm_chart/values.yaml
- kubernetes-agent/insightfinder/insightfinder.go
- kubernetes-agent/kubernetes/dataModel.go
- kubernetes-agent/kubernetes/kubernetes.go
- kubernetes-agent/main.go
- kubernetes-agent/tools/LogData.go
- kubernetes-agent/tools/eventData.go
- kubernetes-agent/tools/instanceMapper.go
- kubernetes-agent/tools/metricData.go
- kubernetes-agent/tools/utility.go
- Added support for `Event` data streaming in Kubernetes agent.
- Add the configuration for `ClusterRole`
- Set default component name for hosts to `k8s Hosts`
- Reduce the memory usage for `InstanceMapper` by using "pass by reference" variable allocation.
> Upgrade Kubernetes agent to 0.0.4

- kubernetes-agent/tools/metricData.go
Skip sending data when the instance name is empty.
> [Kubernetes Agent] Skip sending data when the instance name is empty.

- elasticsearch_collector/getmessages_elasticsearch_collector.py
Add some log prints to debug the ElasticSearch Agent issue in Dell.
> Add more debug lines to ElasticSearch Agent.

- action_server/app.py
- action_server/requirements.txt
https://insightfinders.atlassian.net/browse/II-16345
> add container name

- zabbix/conf.d/config.ini.template
- zabbix/getmessages_zabbix.py
https://insightfinders.atlassian.net/browse/II-16674
> II-16674 Zabbix agent to support metric_disallowlist

- kubernetes-agent/tools/instanceMapper.go
https://insightfinders.atlassian.net/browse/II-17168
> [Kubernetes Agent] Fix the logic to process StatefulSet mapping.

- jaeger/jaeger_client/jaeger_client.go
- jaeger/jaeger_client/traceReponseBody.go
- jaeger/jaeger_client/utils.go
- jaeger/main.go
https://insightfinders.atlassian.net/browse/II-17181
> Add logic to transform Trace Tags array to dictionary

- elasticsearch_collector/getmessages_elasticsearch_collector.py
https://insightfinders.atlassian.net/browse/II-17329
> Fix ElasticSearch agent wrong histocial range issue

- prometheus/conf.d/config.ini.template
Fix Prometheus default agent value.
> Fix prometheus default agent value.

- prometheus/setup/install_cron.sh
Fix bug of install_cron.sh in prometheus/setup/, and make it also work with dependent packages installed in the system.
> Fix install_cron.sh

- loki-audit-log/loki/dataModel.go
- loki-audit-log/loki/loki.go
- loki-audit-log/main.go
https://insightfinders.atlassian.net/browse/II-17352
> Update Loki agent to support audit logs.

- logFileReplay-go/collectors/logfilereplay/logfilereplay.go
New logic:
- Check if the timestamp string is a numerical timestamp or String timestamp like "2024-07-01 00:00:00"
- If the timestamp is digital, use it and convert it to a unixmili timestamp.
- Else: convert it with `carbon` to a unixmili timstamp.
> [log-filereplay-agent-go] Add support for digital timestamp in the parsing logic.

- logFileReplay-go/collectors/logfilereplay/logfilereplay.go
- logFileReplay-go/conf.d/config.ini.template
- Fix logging when missing timestamp or instance field.
- Fix the default instance logic.
> [log-file-replay-agent] Fix logging when missing timestamp or instance field.

- prometheus/conf.d/config.ini.template
- prometheus/getmessages_prometheus.py
> Prometheus agent update to add instance name suffix

- logFileReplay-go/collectors/logfilereplay/config.go
- logFileReplay-go/collectors/logfilereplay/logfilereplay.go
- logFileReplay-go/conf.d/config.ini.template
Add the option:
```
log_raw_data_field = data
```
> Add raw log streaming option to LogFileReplay agent.

- localcron/Dockerfile
- localcron/local-cron.py
https://insightfinders.atlassian.net/browse/II-17869
Save the local-cron.py and dockerfile here to auto build to use in helm chart.
> II-17869 Add localcron and its dockerfile which is used for helm chart

- elasticsearch_collector/Dockerfile
https://insightfinders.atlassian.net/browse/II-17883
> II-17883 Fix elasticsearch collector CVE

- prometheus/Dockerfile
- prometheus/requirements.txt
https://insightfinders.atlassian.net/browse/II-17883
> II-17883 Update prometheus dockerfile to fix CVE

- localcron/Dockerfile
- localcron/local-cron.py
https://insightfinders.atlassian.net/browse/II-17883
> II-17883 Update localcron to use python3 and bitnami/python base image

- prometheus/conf.d/config.ini.template
- prometheus/getmessages_prometheus.py
https://insightfinders.atlassian.net/browse/II-18077
> II-18077 911 Fix broken Redis metrics in Visa

- kubernetes-agent/go.mod
- kubernetes-agent/go.sum
- kubernetes-agent/kubernetes/kubernetes.go
https://insightfinders.atlassian.net/browse/II-18102
> II-18102 Update Kubernetes Agent to fix OOMKilled events.

- prometheus/getmessages_prometheus.py
Fix NaN / Infinity values in Prometheus agent for Visa.
> Fix NaN / Infinity values in Prometheus agent for Visa.

- prometheus/getmessages_prometheus.py
https://insightfinders.atlassian.net/browse/II-18105
> II-18105 Prometheus Agent sending data to all metrics if device field not found

- prometheus/conf.d/config.ini.template
- prometheus/getmessages_prometheus.py
https://insightfinders.atlassian.net/browse/II-18418
1. Switch to use seconds for `run_interval` and `smapling_interval` in config template.
2. Switch to use seconds during project creation.
3. Update Prometheus Query API to range query.
> II-18418 Update Prometheus agent to support subsecond streaming

- zabbix/conf.d/config.ini.template
- zabbix/getmessages_zabbix.py
- zabbix/requirements.txt
https://insightfinders.atlassian.net/browse/II-18611
> II-18611 Update zabbix agent icmp metric to ms.

- zabbix/getmessages_zabbix.py
https://insightfinders.atlassian.net/browse/II-18983
> Update Zabbix agent to skip resolved problems

- kubernetes-agent/README.md
Fix readme file in kubernetes-agent
> Fix readme file in kubernetes-agent

- rag-file-agent/config.yaml
- rag-file-agent/rag-file-uploader-md.py
- rag-file-agent/requirements.txt
https://insightfinders.atlassian.net/browse/II-19035
> Ii 19035 general rag uploader agent

- zabbix/conf.d/config.ini.template
- zabbix/getmessages_zabbix.py
https://insightfinders.atlassian.net/browse/II-19049
> Update zabbix agent to support component regex and zone info.

- rag-file-agent/rag-file-uploader-md.py
- rag-file-agent/requirements.txt
https://insightfinders.atlassian.net/browse/II-19039
> Add support for JSON data uploading for RAG uploader.

- zabbix/getmessages_zabbix.py
https://insightfinders.atlassian.net/browse/II-19049
> Fix Zabbix agent multi-threading freeze issue.

- kubernetes-agent/insightfinder/logDataModel.go
- kubernetes-agent/insightfinder/metricDataModel.go
- kubernetes-agent/kubernetes/kubernetes.go
- kubernetes-agent/tools/LogData.go
- kubernetes-agent/tools/instanceMapper.go
- kubernetes-agent/tools/metricData.go
https://insightfinders.atlassian.net/browse/II-19174
> add zone data to log and metric payload

- prometheus/conf.d/config.ini.template
- prometheus/getmessages_prometheus.py
https://insightfinders.atlassian.net/browse/II-19229
> Add container type support to prometheus agent.

- zabbix/getmessages_zabbix.py
https://insightfinders.atlassian.net/browse/II-19049
> Add Zone info to problems projects in Zabbix agent

- webhook/Dockerfile
- webhook/README.md
- webhook/config.yaml
- webhook/go.mod
- webhook/go.sum
- webhook/helm-chart/Chart.yaml
- webhook/helm-chart/templates/NOTES.txt
- webhook/helm-chart/templates/_helpers.tpl
- webhook/helm-chart/templates/configmap.yaml
- webhook/helm-chart/templates/deployment.yaml
- webhook/helm-chart/values.yaml
- webhook/main.go
- webhook/start.sh
Add docker image and helm chart to the webhook agent
> Add docker image and helm chart to the webhook agent

- logFileReplay-csv/requirements.txt
- logFileReplay-csv/send_csv_data_py3.py
Add support for json field to logfilereplay-csv agent.
> Add support for json field to logfilereplay-csv agent.

- zabbix/getmessages_zabbix.py
Fix zabbix alert data streaming.
> Fix zabbix alert data streaming.

- zabbix/getmessages_zabbix.py
Fix zabbix agent alert streaming for BAI
> Fix zabbix agent alert streaming for BAI

- elasticsearch_collector/getmessages_elasticsearch_collector.py
- redis-agent/conf.d/config.ini.template
https://insightfinders.atlassian.net/browse/II-19801
> fixed timestamp parsing bug in elastic agent

- ruckus-agent/insightfinder/insightfinder.go
Convert timestamp to epoch milliseconds
> Convert timestamp to epoch milliseconds in SendMetricsBulk if in seconds

- zabbix/getmessages_zabbix.py
https://insightfinders.atlassian.net/browse/II-19851
> II-19851 Zabbix Agent - Fix Instance Name and Component Name

- prometheus-go/.gitignore
- prometheus-go/conf.d/config.ini.template
- prometheus-go/conf.d/query.json
- prometheus-go/insightfinder/insightfinder.go
- prometheus-go/run.ps1
https://insightfinders.atlassian.net/browse/II-19883
* Added `prometheus-go/conf.d/config.ini.template` with detailed Prometheus and InsightFinder configuration options, including support for metrics queries, authentication, and project settings.
* Added `prometheus-go/conf.d/query.json` to specify Prometheus queries for metrics filtering.
* Updated `prometheus-go/insightfinder/insightfinder.go` to fix the sampling interval logic by removing unnecessary division and ensuring the interval is consistent across fields.
* Added `prometheus-go/run.ps1`, a PowerShell script to run `insightagent-go.exe` every minute, with logging and error handling for better execution management.
* Removed redundant entries from `.gitignore` in the `prometheus-go` directory.
> II-19883 Fix Prometheus Go agent.

- zabbix/getmessages_zabbix.py
https://insightfinders.atlassian.net/browse/II-19884
> II-19884 - AccessParks - Add IP address to zabbix agent

- prometheus/getmessages_prometheus.py
https://insightfinders.atlassian.net/browse/II-19979
> II-19979: Fix Prometheus Agent Parsing issues

- logFileReplay-go/collectors/logfilereplay/logfilereplay.go
https://insightfinders.atlassian.net/browse/II-20066
> II-20066 Replace the decoder in file processor in log-file-replay-agent

- logFileReplay-go/collectors/logfilereplay/logfilereplay.go
- logFileReplay-go/conf.d/config.ini.template
https://insightfinders.atlassian.net/browse/II-20066
> II-20066 Support multiple instance field options in the config file.

- logFileReplay-go/collectors/logfilereplay/config.go
- logFileReplay-go/collectors/logfilereplay/logfilereplay.go
- logFileReplay-go/conf.d/config.ini.template
https://insightfinders.atlassian.net/browse/II-20066
> II-20066 Add configuration item for default component name.

- zabbix-component-with-tag/update_zabbix_components_with_tag.py
Add regex for CN and DN devices.
> Add regex for CN and DN devices.

- prometheus-k8s/.gitignore
- prometheus-k8s/Dockerfile
- prometheus-k8s/agent.txt
- prometheus-k8s/conf.d/config.ini.template
- prometheus-k8s/conf.d/prometheus_query.json
- prometheus-k8s/cron.py
- prometheus-k8s/getmessages_prometheus.py
- prometheus-k8s/ifobfuscate.py
- prometheus-k8s/leader_election_wrapper.py
- prometheus-k8s/requirements.txt
https://insightfinders.atlassian.net/browse/II-20168
> Ii 20168 add leader election to prometheus agent

- ruckus-agent/go.mod
- ruckus-agent/pkg/models/models.go
- ruckus-agent/ruckus/client_data.go
- ruckus-agent/ruckus/type.go
- ruckus-agent/worker/worker.go
https://insightfinders.atlassian.net/browse/II-20445
> [II-20445] AccessParks - Add RSSI, SNR to the Ruckus agent

- elasticsearch_collector-k8s/.dockerignore
- elasticsearch_collector-k8s/.gitignore
- elasticsearch_collector-k8s/Dockerfile
- elasticsearch_collector-k8s/agent.txt
- elasticsearch_collector-k8s/conf.d/config.ini.template
- elasticsearch_collector-k8s/conf.d/query_json.json
- elasticsearch_collector-k8s/cron.py
- elasticsearch_collector-k8s/getmessages_elasticsearch_collector.py
- elasticsearch_collector-k8s/ifobfuscate.py
- elasticsearch_collector-k8s/leader_election_wrapper.py
- elasticsearch_collector-k8s/requirements.txt
https://insightfinders.atlassian.net/browse/II-20167
> II-20167-Add-leader-election-to-elasticsearch-agent

- ruckus-agent/configs/config.go
- ruckus-agent/configs/config.yaml
- ruckus-agent/configs/type.go
- ruckus-agent/metric_filter_example.md
- ruckus-agent/pkg/models/models.go
- ruckus-agent/worker/test_local.go
- ruckus-agent/worker/v1_send_data.go
- ruckus-agent/worker/worker.go
https://insightfinders.atlassian.net/browse/II-20830
> II-20830 AccessParks - configurable metric data streaming - ruckus

- cambium-agent/cambium/cambium.go
- cambium-agent/config/config.go
- cambium-agent/config/config.yaml
- cambium-agent/metric_filter_example.md
https://insightfinders.atlassian.net/browse/II-20828
> [II-20820] AccessParks - configurable metric data streaming - cambium

- cambium-agent/cambium/cambium.go
- cambium-agent/config/config.go
- cambium-agent/config/config.yaml
- ruckus-agent/configs/config.go
- ruckus-agent/configs/config.yaml
- ruckus-agent/configs/type.go
- ruckus-agent/ruckus/client_data.go
- ruckus-agent/worker/worker.go
https://insightfinders.atlassian.net/browse/II-20846
> II-20846 AccessParks - Modify cambium and ruckus agent for rssi and snr for number of clients in config.yaml

- response-time/config.ini
- response-time/main.py
Add LLM monitoring to the code.
> Add LLM monitoring to the code.
